### ISSUE TITLE
ViewResult - Local variable layoutReady used without being initialized

### ISSUE THREAD

**Issue by mikedotalmond** [ufront/ufront-mvc#10]
I'm trying out Haxe 3.2 rc1 and get this error from ufront-mvc 1,0,0-rc,15 (haxelib)

Here's the line:
https://github.com/ufront/ufront-mvc/blob/445e7741f6b5e67a11ffb8704ca9d08df90e1237/src/ufront/web/result/ViewResult.hx#L430

I'm currently 'fixing' / working around it by initialising `layoutReady` as null, here:  https://github.com/ufront/ufront-mvc/blob/445e7741f6b5e67a11ffb8704ca9d08df90e1237/src/ufront/web/result/ViewResult.hx#L398

(though I don't know the codebase well enough to be sure it won't have side-effects... so reporting issue rather than creating a pr :)

Incidentally - thanks for ufront!

**Comment by jasononeil** [comment]
Thanks for reporting it!

I'll take a look and get 3.2 support working this week.

**Comment by mikedotalmond** [comment]
Cheers. I'm not sure if it's a 3.2 thing, or a peculiarity with my set-up after updating to 3.2rc1 -- I'm also seeing what looks like a pretty odd variable initialisation issue on another (non-ufront) project I tried compiling lately.

**Comment by jasononeil** [comment]
Hi @mikedotalmond, fixed this one, still got a few more 3.2 related bugs to work through.  I'll push a new version to haxelib once it's ready!
