### ISSUE TITLE
injectClass(apiClass) causes circular reference if api references each other

### ISSUE THREAD

**Issue by kevinresol** [ufront/ufront-mvc#21]
need to use `mapSingleton` instead

e.g.
https://github.com/ufront/ufront-mvc/blob/master/src/ufront/app/UfrontApplication.hx#L107
https://github.com/ufront/hello/blob/master/src/Tasks.hx#L41

**Comment by jasononeil** [comment]
Good pick-up.  Thanks for reporting....
