### ISSUE TITLE
context is null in @post in a Controller

### ISSUE THREAD

**Issue by kevinresol** [ufront/ufront-mvc#22]
```haxe
// MyController.hx:
@post
public function init()
{
  trace(context == null); // true
}

@:route(GET, "/")
public function home()
{
  trace(context == null); // false
}
```

This bug appeared in the dev version because I have been doing `ViewResult.globalValues["uri"] = context.request.uri` inside `@post` for a while until it became broken when I switched to the dev version.

**Comment by jasononeil** [comment]
This is a minject dev problem again, I'll address it soon...

For anyone else encountering it, a workaround I found was to use:

    @inject public function init(context:HttpContext) {...}

instead of 

    @post public function init() { this.context... }

**Comment by jasononeil** [comment]
This has been solved in the latest minject.  If there's still any issues let me know!
