### ISSUE TITLE
ClientJS: in-page js not executed when using client to render page

### ISSUE THREAD

**Issue by kevinresol** [ufront/ufront-mvc#23]
Any `<script>` tag will be only executed when the page is rendered by server and not if the page is rendered by client. That means many js-based UI won't work if the page is rendered by clientJS.

**Comment by kevinresol** [comment]
Maybe related: http://stackoverflow.com/questions/610995/cant-append-script-element

**Comment by jasononeil** [comment]
There's a bigger question of how JS client-side actions should be triggered (and perhaps persisted) as well.  I'll have to give some thought to it.

Thanks for the link...

**Comment by kevinresol** [comment]
http://stackoverflow.com/a/3603496 I think I will try to use the solution in this particular answer to fix the problem, by looking through the document and find out any script tags and re-execute them

**Comment by jasononeil** [comment]
Yeah that does look good.  If we could integrate that solution into [CallJavascriptResult](http://api.ufront.net/ufront/web/result/CallJavascriptResult.html) that might be a good solution.
