### ISSUE TITLE
What's left for nodejs backend support?

### ISSUE THREAD

**Issue by fullofcaffeine** [ufront/ufront-mvc#27]
Hey Jason!

I remember we briefly talked about the nodejs backend for UFront, and you said it's partially implemented. I'm wondering what's exactly left to implement / what are the main challenges there? Maybe we could break them down into specific issues to tackle here? I'd love to help.

Cheers.

**Comment by jasononeil** [comment]
Hi Marcelo, sorry for the late reply!

The latest ufront-mvc release filled in many of the missing pieces for NodeJS support, including:

* Using the official Haxe Foundation NodeJS externs: https://github.com/HaxeFoundation/hxnodejs/ 
* Using Franco's Express externs: https://github.com/abedev/hxexpress
* Providing a FileSession implementation (that's all async friendly)
* Providing a FileViewEngine implementation (also async friendly)
* The HelloWorld example has been updated to work with NodeJS.

In terms of what is left:

* There are some holes in the NodeJS HttpRequest object, see documentation on: http://api.ufront.net/nodejs/ufront/web/context/HttpRequest.html
    * Fixing the remaining inconsistencies with request parameters etc.
    * Get parseMultipartUpload / postString working.
* Testing!  
    * Try getting the Hello World example working.  (Easiest way will be to clone the `ufront` repo and all submodules, and then run `./setupDev` to use the latest versions of each library, and the externs etc.)  
    * If that works, then experiment with other more complex things.
* Currently `ufront-orm` is based entirely on `sys.db`, so won't work on NodeJS.  That also means it won't work with `ufront-easyauth` or `ufront-ufadmin`.  D'OH!  I have a plan to make ufront-orm work with an asynchronous database manager, but it might take a while.  In the mean time, it would be good to:
    * Create some externs that work with [UFCache](http://api.ufront.net/ufront/cache/UFCache.html) - Maybe Redis or Memcached or similar?  These would let you use [CacheSession](http://api.ufront.net/ufront/web/session/CacheSession.html) and a few other goodies.
    * Create a [UFAuthHandler](http://api.ufront.net/ufront/auth/UFAuthHandler.html) that works using something easy on NodeJS.  Maybe an auth system that works with express already, something that uses NoSQL, etc.
* Dreaming: I would love to implement Haxe remoting over web sockets with socket.io or similar :)

---

So thanks for the offer to help - honestly the most helpful thing will be to try get the environment up and running, compile the hello world, and experiment and let me know what I should be fixing or working on next :)

I'm going to close this issue - but feel free to open as many as you want with bug reports or feature requests or ideas... and if you have questions or need help ask on Gitter and I'll do my best to help.
