### ISSUE TITLE
FileSession: wrong php code being generated

### ISSUE THREAD

**Issue by kevinresol** [ufront/ufront-mvc#28]
This line: https://github.com/ufront/ufront-mvc/blob/master/src/ufront/web/session/FileSession.hx#L225

in php is generated as:
`$tmp = null->asGoodSurprise();` which is a syntax error. (`->` cannot be used on `null`)

**Comment by kevinresol** [comment]
Seems that it is a haxe issue. Track at https://github.com/HaxeFoundation/haxe/issues/4434 instead

**Comment by kevinresol** [comment]
Well since haxe doesn't want to fix that, ufront has to...

**Comment by jasononeil** [comment]
Thanks for picking that up.  I understand Simon's reasoning... I just overlooked it when refactoring these recently.  It'll be an easy fix, I'll try write some unit tests too.
