### ISSUE TITLE
GET requests percent-encode UTF-8 characters

### ISSUE THREAD

**Issue by dstrekelj** [ufront/ufront-mvc#3]
As requested, I'm submitting a new issue based on [this question](https://groups.google.com/forum/#!topic/haxelang/qtss1QwXDsk) from the Haxe mailing list.

---

**The Code**

Let's say I have a simple index view with a form in it. The form has one field - `name` - and a submit button. The form's action attribute links to the `/action/submit/` route, which is associated with the `submit` action method. That method returns the submitted `name` field by HTTP POST request to the index route.

The index route requests data in the form of the `$name` variable by HTTP GET request. The requested data is returned in a new `ViewResult` to print a simple "Hello, $name" string.

```haxe
@:route("/$name", GET)
public function index(?name : String = "stranger")
{
	return new ViewResult({
		greeting: 'Hello, $name.',
	});
}

@:route("/action/submit/", POST)
public function submit(args : {name : String})
{
	return new RedirectResult(Config.app.basePath + args.name);
}
```

---

**The Result**

Submitting ASCII characters results in the index route printing ASCII characters, as expected.

Submitting UTF-8 characters (such as č, ć, ž, đ, š) results in the index route printing percent-encoded characters (%C4%8D, %C4%87, %C5%BE, %C4%91, %C5%A1).

The data seems to be encoded when received by GET request. Whatever is submitted shows to be unaffected when directly returning the content in the `submit` action (by `return args.name`).

---

**The *Expected* Result**

UTF-8 characters (such as č, ć, ž, đ, š) and other percent-encoded characters are decoded when passed to an action method. The data submitted by the form is consistent with what was received by GET request.

---

**The Solution (for now)**

Currently, the only way to avoid percent-encoding is by using the `StringTools.urlDecode()` method on what is passed to the index route.

---

**The Question**

Should this be taken care of internally?

**Comment by jasononeil** [comment]
I've applied a `StringTools.urlDecode()` to all both `request.query`, `request.post` and `request.uri`.  Thanks for taking the time to write a bug report, and sorry it took me a while to get too :)

I'll release a new ufront-mvc on haxelib soon.

**Comment by jasononeil** [comment]
FYI it looks like this doesn't work on nekotools server... but does work with mod_neko.  I'll have to investigate further.
