### ISSUE TITLE
Compiler reports incorrect error position

### ISSUE THREAD

**Issue by kevinresol** [ufront/ufront-mvc#35]
I am always having the compile error being "masked" by macro

something like this: 
```
src/controller/AuthController.hx:24: lines 24-57 : Failed to parse function argument `args`.  The args object must contain only the types String, Int, Float and Bool. 
src/controller/AuthController.hx:24: lines 24-57 : Unexpected }
```

Note that the `unepxcted }`is not at AuthController.hx:24: lines 24-57, it is at somewhere else (maybe in an API)

**Comment by jasononeil** [comment]
Hey @kevinresol , I've committed a change that will make sure neither ControllerMacros nor ApiMacros will "swallow" the error message.

Unfortunately it makes for some situations where both an error and a warning are reported, at different positions, for the same problem.  It's quite hard to know which position is the correct one to display, so I'm just displaying both for now.

We can have a go at a better solution another time if needed.

**Comment by kevinresol** [comment]
:+1: thanks!
