### ISSUE TITLE
Can't compile Client part of the application

### ISSUE THREAD

**Issue by MangelMaxime** [ufront/ufront-mvc#39]
Hello,
I got an error when trying to compile my `Client.hx` using `ufront b`

Client.hx
```haxe
package;

import ufront.MVC;


/**
 * ...
 * @author Shadaen
 */
class Client
{
	static var jsApp:ClientJsApplication;
	
	static function main()
	{
		jsApp = new ClientJsApplication({
			indexController: app.Routes, 
			templatingEngines: [TemplatingEngines.haxe], 
			defaultLayout: Config.app.defaultLayout, 
			basePath: Config.app.basePath			 
		});
		
		jsApp.listen();
	}
}
```

Client.hxml
```
	-lib ufront-client

	-cp src
	-main Client

	-js www/client.js 

```

Here is my error when trying to compile.

```
F:\hybris-tracker\hybris-tracker>ufront b
Build client.hxml
E:\HaxeToolkit\haxe\lib\ufront-mvc/1,0,1/src/ufront/core/InjectionTools.hx:5: characters 7-28 : Type
 not found : minject.InjectorMacro
Build server.hxml
Failed to build client.hxml`
```

I think it's coming from the lib `minject` but I am not sure.

**Comment by jasononeil** [comment]
That sounds to me like it's got the wrong version of minject being used.

If you run `haxelib list minject` it should show the versions, the correct one is `[2.0.0-rc.1]`.

If that's not the issue, post back with which versions you're using / have installed and re-open the issue :)

Hope that helps!
