### ISSUE TITLE
ClientAction fails when no chaining

### ISSUE THREAD

**Issue by postite** [ufront/ufront-mvc#58]
this won't work:

    var p=new PartialViewResult({val:"bip"},"index");
    p.addClientAction(Loading);
    return p;

an this will:

	 return new PartialViewResult({val:"bip"},"index")
	.addClientAction(Loading);

**Comment by kevinresol** [comment]
Because you have to return the `AddClientActionResult` instead of `PartialViewResult` in order for your client action to work.
