### ISSUE TITLE
Serving on localhost with different hostname

### ISSUE THREAD

**Issue by vrescobar** [ufront/ufront-mvc#60]
Hello,

I just followed the HelloWorld tutorial until I decided to test it by using the default neko server.

By my surprise when starting a neko server, it started a server using my hostname name at the default port, but it wasn't visible until I changed my local hostname to "localhost".

    $ haxelib run ufront server
    # Switching directory to www
    # Starting Neko Server on newhope:2987

For sure I could fix it by adding an entry in /etc/hosts pointing to 127.0.0.1, but couldn't just the default server use 127.0.0.1 instead? By using other programs to serve from local filesystem never has such issue.

**Comment by kevinresol** [comment]
This is because ufront calls `Host.localhost().toString()` to get the host name. And that is neko's matter returning non-"localhost" values. 

A workaround is to explicitly specify your host name: `ufront server --host localhost`
