### ISSUE TITLE
Switch to new minject

### ISSUE THREAD

**Issue by jasononeil** [ufront/ufront-mvc#7]
See:

https://github.com/massiveinteractive/minject/pull/34

This will also let us get rid of the `InjectionRef` type.

**Comment by jasononeil** [comment]
Okay, `minject:2.0.0` has not been released, but I've been promised it will be released during May, before the WWX conference.  So I've gone ahead and made the changes.

If you are using the development version of `ufront-mvc`, you'll need to use the git version of minject:

    haxelib git minject git@github.com:massiveinteractive/minject.git v2 src/

**Comment by MichaPooh** [comment]
Hello
I had to change in ufront.core.InjectionTools (line:26)
```
var className = InjectorMacro.getType( whenAskedFor );
```
to
```
var className = InjectorMacro.getTypeName( whenAskedFor );
```

to be able to compile my project with the latest git version of ufront-mvc

on the other side I am no longer able to use an inject chain on my ClientJsApplication instance,
the method is still there in ClientJsApplication but it seems gone in HttpApplication 
(obligatory to use injectClass or injectValue now ??)
